### ISSUE TITLE
TCGA abbreviation and cancer type were wrong.

### ISSUE THREAD

**Issue by yyoshiaki** [biocore/tcga#20]
In the browser [http://cancermicrobiome.ucsd.edu/CancerMicrobiome_DataBrowser/](http://cancermicrobiome.ucsd.edu/CancerMicrobiome_DataBrowser/), 

|TCGA Abbreviation|cancer type|
|--|--|
|TCGA-THCA | Thymoma |
|TCGA-THYM | Thyroid Carcinoma |

is wrong. Correctly, it is 

|TCGA Abbreviation|cancer type|
|--|--|
|TCGA-THCA | Thyroid Carcinoma |
|TCGA-THYM | Thymoma |

**Comment by gregpoore** [comment]
Hi @yyoshiaki, thanks a bunch for catching that! The table on the left-side of the browser that shows the abbreviation and meaning is distinct from the actual results (in R Shiny, it's actually loading a separate data frame), so the rest of the results displayed are still fine. I'll make this change soon and will close the issue then.

**Comment by gregpoore** [comment]
Website now fixed
