### ISSUE TITLE
Pseudo-contaminants into the raw data

### ISSUE THREAD

**Issue by Anaskou** [biocore/tcga#27]
Hello, 

Can you specify which were the pseudo-contaminants that you spiked into the raw data in order to track them through the downstream analysis? For all 5 types of pseudo-contaminants did you use the same reads? Also, the reads came from an organism that is biological irrelevant to your study and so you did not expect to find any reads assigned to this organism, or your pseudo-contaminants were artificial reads? 

Thank you very much

**Comment by gregpoore** [comment]
Hi there, the pseudo-contaminants were artificial reads. Each pseudo-contaminant was generated independently, as described in the paper's methods:

_[...] we spiked five pseudo-contaminants into the raw data set (Extended Data Fig. [6a](https://www.nature.com/articles/s41586-020-2095-1#Fig10), top right) to track them through decontamination, SNM, and ML. This included the following: (1) 1,000 reads across all samples from HMS; (2) 1,000 reads across all samples from HMS, Baylor College of Medicine, Washington University School of Medicine, and Canada’s Michael Smith Genome Sciences Centre; (3) 1,000 reads across all samples from all sequencing centres; (4) 10<sup>6</sup> reads spiked across 100 randomly selected samples from HMS; and (5) 10<sup>6</sup> reads spiked across 1,000 randomly selected samples from all sequencing centres. The mean raw read count across all samples and taxa was 1,481.20, so pseudo-contaminants containing 1,000 reads can be considered ‘low-level’ background while those with 10<sup>6</sup> reads are considered ‘high-abundance’ spikes._
